### PR TITLE
Added maps without grid on renewal areas

### PR DESCRIPTION
**Pull request by Daegaladh**
Added maps without grid on renewal areas.

### CODE REVIEW

**Comment by zackdreaver** [comment]
I can only find malangdo map that was removed in Midgard map, 
is there any other map that you added to or removed from Midgard?

**Comment by Daegaladh** [comment]
Nope, that's the only difference.

**Comment by zackdreaver** [comment]
Ok, it's looks good to me,
is there anything else that you want to add to this PR?

**Comment by Daegaladh** [comment]
That's all :+1:

**Comment by zackdreaver** [comment]
Alright let's merge it.
Thank you for your contribution.

**Pull request merged**
